project_id = "evyjuxnninzuywytbbzt"

[functions.kai-background-removal]
verify_jwt = false

[functions.kai-proxy]
verify_jwt = false

[functions.kai-webhook-proxy]
verify_jwt = false

[functions.maple-scrape]
verify_jwt = false

[functions.maple-pdp-analyze]
verify_jwt = false

[functions.fotor-background-removal]
verify_jwt = false

[functions.ben-extract-images]
verify_jwt = false

[functions.ben-process-images]
verify_jwt = false

[functions.send-crew-request-email]
verify_jwt = false

[functions.anita-extract-carousel]
verify_jwt = false

[functions.anita-generate-lifestyle]
verify_jwt = false
